- name: Install Kubernetes
  hosts: all
  become: true
  tasks:

    - name: Create Kubernetes Cluster
      shell: |
        kubeadm init --cri-socket {{ cri_scoket }} --control-plane-endpoint="{{ control_plane_address }}:6443" --upload-certs --apiserver-advertise-address=0.0.0.0 --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans={{ cert_extra_dns_addresses }}

    - name: Configure kubeadmin
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
