- name: Install Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Stop Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Add Kubernetes Repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: | 
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key

    - name: Set Kubernetes CRI Conf
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: | 
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Set Containerd Module Load Conf
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: | 
          overlay
          br_netfilter

    - name: Set K8S Module Load Conf
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: | 
          overlay
          br_netfilter
    
    - name: Add the overlay module
      modprobe:
        name: overlay
        state: present
    - name: Add the br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Load System
      shell: |
        sysctl --system

        
    - name: Disable Swap
      shell: |
        swapoff -a 
        sed -i '/ swap / s/^/#/' /etc/fstab
        mount -a
        free -h

    - name: Add Docker CE Repo
      dnf:
        name: "https://download.docker.com/linux/centos/docker-ce.repo"
        state: present
        
    - name: Install DNF Modules
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - iproute-tc
        state: latest

    - name: Remove Old Modules
      yum:
        name: "{{ packages }}"
        state: abstent
      loop:
        - buildah
        - skopeo
        - podman
        - containers-common
        - atomic-registries
        - docker
        - container-tools

    - name: Remove Old Files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/containers/*
        - /var/lib/containers/*
        - /etc/docker
        - /etc/subuid*
        - /etc/subgid*
        - ~/.local/share/containers/
        
    - name: Install Necessary Modules
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        - go-toolset

    - name: Install Containetd
      dnf:
        name:
          - containerd.io
        state: latest
        
    - name: Create Containerd Container DIR
      file:
        path: /rsm-kubernetes
        state: directory
        
    - name: Copy Containerd Conf
      get_url:
        url: https://raw.githubusercontent.com/umitkarabudak-ICW/ansible/main/playbooks/conf/containerd/config.toml
        dest: /etc/containerd/conf.toml
        

    - name: Enable Containerd and Restart
      systemd:
        state: restarted
        daemon_reload: true
        name: containerd
