- name: Install Kubernetes Keepalived and HAProxy
  hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - keepalived 
        - haproxy
        
    - name: Create keepalived sh file
      shell: |
        cat >> /etc/keepalived/check_apiserver.sh <<EOF
        #!/bin/sh

        errorExit() {
          echo "*** $@" 1>&2
          exit 1
        }

        curl --silent --max-time 2 --insecure https://localhost:6443/ -o /dev/null || errorExit "Error GET https://localhost:6443/"
        if ip addr | grep -q {{ lb_search_start_ip }}; then
          curl --silent --max-time 2 --insecure https://{{ lb_virtual_ipaddress }}:6443/ -o /dev/null || errorExit "Error GET https://{{ lb_virtual_ipaddress }}:6443/"
        fi
        EOF
        chmod +x /etc/keepalived/check_apiserver.sh
        
        
    - name: Configure Keepalived
      shell: |
        cat >> /etc/keepalived/keepalived.conf <<EOF
        vrrp_script check_apiserver {
          script "/etc/keepalived/check_apiserver.sh"
          interval 3
          timeout 10
          fall 5
          rise 2
          weight -2
        }

        vrrp_instance VI_1 {
            state {{ state }}
            interface {{ interface }}
            virtual_router_id 1
            priority {{ priority }}
            advert_int 5
            authentication {
                auth_type PASS
                auth_pass {{ auth_pass }}
            }
            virtual_ipaddress {
                {{ lb_virtual_ipaddress }}
            }
            track_script {
                check_apiserver
            }
        }
        EOF
        
    - name: Enable Keepalived
      systemd:
        name: keepalived
        enabled: true
        
    - name: Configure HAProxy
      shell: |       
        cat >> /etc/haproxy/haproxy.cfg <<EOF

        frontend kubernetes-frontend
          bind *:6443
          mode tcp
          option tcplog
          default_backend kubernetes-backend

        backend kubernetes-backend
          option httpchk GET /healthz
          http-check expect status 200
          mode tcp
          option ssl-hello-chk
          balance roundrobin
            server rsm-esy-kmaster 10.86.39.165:6443 check fall 3 rise 2
            server rsm-ank-kmaster 10.86.39.166:6443 check fall 3 rise 2
        EOF
        
    - name: Enable HAProxy
      systemd:
        name: haproxy
        enabled: true    

    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: true
      loop:
        - keepalived
        - haproxy
      
